---
- name: update Ubuntu repo cache
  apt: update_cache=yes
  sudo: yes
- name: install ubuntu system 
  apt: name={{ item }} state=present
  with_items: mongodb_packages #This is defined in group_vars/compute file
  sudo: yes
  tags: install
- name: install pip mongo packages
  pip: name={{ item }} state=present
  with_items: mongodb_pip_packages
  sudo: yes
  tags: install

