---
# - name: update Ubuntu repo cache
#   apt: update_cache=yes
#   sudo: yes
- name: install ubuntu system 
  apt: name={{ item }} state=present
  with_items: redis_packages #This is defined in ../vars/main.yml file
  sudo: yes
  tags: install
#- name: install pip redis packages
#  pip: name= {{ item }} state=present
#  with_items: redis_pip_packages
#  sudo: yes
#  tags: install
#
