---
- name: update Ubuntu repo cache
  apt: update_cache=yes
  sudo: yes
  tags: update_cache
- name: install pip
  apt: name=python-pip state=present
  sudo: yes
- name: install git
  apt: name=git state=present
